title:              Brezno - Podcast za poglabljanje zavesti
email:              your-email@example.com
description:        Podcast za poglabljanje svoje zavesti s pomočjo hipnotične indukcije, zvokov narave in glasbil
author:             Klemen Nagode
baseurl:            ""
url:                "https://brezno.org"

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
